"""Initial schema creation

Revision ID: 4d10ca346bc1
Revises: 
Create Date: 2025-08-28 22:51:00.044050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d10ca346bc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_tick', sa.DateTime(), nullable=True),
    sa.Column('last_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instruments_last_tick', 'instruments', ['last_tick'], unique=False)
    op.create_index('ix_instruments_symbol', 'instruments', ['symbol'], unique=False)
    op.create_index('ix_instruments_type_status', 'instruments', ['type', 'status'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_window_seconds', sa.Integer(), nullable=True),
    sa.Column('moving_average_period', sa.Integer(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rules_active', 'alert_rules', ['active'], unique=False)
    op.create_index('ix_alert_rules_active_instrument', 'alert_rules', ['active', 'instrument_id'], unique=False)
    op.create_index('ix_alert_rules_instrument', 'alert_rules', ['instrument_id'], unique=False)
    op.create_index('ix_alert_rules_last_triggered', 'alert_rules', ['last_triggered'], unique=False)
    op.create_index('ix_alert_rules_type', 'alert_rules', ['rule_type'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('bid', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('ask', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('bid_size', sa.Integer(), nullable=True),
    sa.Column('ask_size', sa.Integer(), nullable=True),
    sa.Column('open_price', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('high_price', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.Column('low_price', sa.DECIMAL(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_instrument', 'market_data', ['instrument_id'], unique=False)
    op.create_index('ix_market_data_latest', 'market_data', ['instrument_id', 'timestamp', 'price'], unique=False)
    op.create_index('ix_market_data_price', 'market_data', ['price'], unique=False)
    op.create_index('ix_market_data_timestamp', 'market_data', ['timestamp'], unique=False)
    op.create_index('ix_market_data_timestamp_instrument', 'market_data', ['timestamp', 'instrument_id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trigger_value', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('threshold_value', sa.DECIMAL(precision=12, scale=4), nullable=False),
    sa.Column('fired_status', sa.String(length=20), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('evaluation_time_ms', sa.Integer(), nullable=True),
    sa.Column('rule_condition', sa.String(length=20), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivery_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_logs_delivery_status', 'alert_logs', ['delivery_status'], unique=False)
    op.create_index('ix_alert_logs_evaluation_time', 'alert_logs', ['evaluation_time_ms'], unique=False)
    op.create_index('ix_alert_logs_fired_status', 'alert_logs', ['fired_status'], unique=False)
    op.create_index('ix_alert_logs_instrument', 'alert_logs', ['instrument_id'], unique=False)
    op.create_index('ix_alert_logs_recent', 'alert_logs', ['timestamp', 'fired_status', 'instrument_id'], unique=False)
    op.create_index('ix_alert_logs_rule', 'alert_logs', ['rule_id'], unique=False)
    op.create_index('ix_alert_logs_rule_timestamp', 'alert_logs', ['rule_id', 'timestamp'], unique=False)
    op.create_index('ix_alert_logs_timestamp', 'alert_logs', ['timestamp'], unique=False)
    op.create_index('ix_alert_logs_timestamp_instrument', 'alert_logs', ['timestamp', 'instrument_id'], unique=False)
    op.create_index('ix_alert_logs_timestamp_rule', 'alert_logs', ['timestamp', 'rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_logs_timestamp_rule', table_name='alert_logs')
    op.drop_index('ix_alert_logs_timestamp_instrument', table_name='alert_logs')
    op.drop_index('ix_alert_logs_timestamp', table_name='alert_logs')
    op.drop_index('ix_alert_logs_rule_timestamp', table_name='alert_logs')
    op.drop_index('ix_alert_logs_rule', table_name='alert_logs')
    op.drop_index('ix_alert_logs_recent', table_name='alert_logs')
    op.drop_index('ix_alert_logs_instrument', table_name='alert_logs')
    op.drop_index('ix_alert_logs_fired_status', table_name='alert_logs')
    op.drop_index('ix_alert_logs_evaluation_time', table_name='alert_logs')
    op.drop_index('ix_alert_logs_delivery_status', table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index('ix_market_data_timestamp_instrument', table_name='market_data')
    op.drop_index('ix_market_data_timestamp', table_name='market_data')
    op.drop_index('ix_market_data_price', table_name='market_data')
    op.drop_index('ix_market_data_latest', table_name='market_data')
    op.drop_index('ix_market_data_instrument', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('ix_alert_rules_type', table_name='alert_rules')
    op.drop_index('ix_alert_rules_last_triggered', table_name='alert_rules')
    op.drop_index('ix_alert_rules_instrument', table_name='alert_rules')
    op.drop_index('ix_alert_rules_active_instrument', table_name='alert_rules')
    op.drop_index('ix_alert_rules_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('ix_instruments_type_status', table_name='instruments')
    op.drop_index('ix_instruments_symbol', table_name='instruments')
    op.drop_index('ix_instruments_last_tick', table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
